config: 2.0
  ##Plugin was created by theiceninja
links:
  store: "&r\n &#00D1FF❆ &#4AF324https://store.ramatninja.tk &#24F39E&lחנות &#00D1FF❆ \n&r"
  youtube: "&r\n &#00D1FF❆ &#F32724https://www.youtube.com/channel/UCDnqgUONgjX5R_h3_Q31sEw &#F33724&lיוטיוב &#00D1FF❆ \n&r"
  namemc: "&r\n &#00D1FF❆ &#24F388https://namemc.com/server/ramatninja.mine.bz &#24F356&lהצבעה &#00D1FF❆ \n&r"
  discord: "&r\n &#00D1FF❆ &#2463F3https://discord.gg/D6k8VJYpyQ &#24B4F3&lדיסקורד &#00D1FF❆ \n&r"
    ##If you want to drop a line in the plugin do \n
    ##If you want to use hex colors use &
