name: Links
version: '1.0-SNAPSHOT'
main: me.theiceninja.links.Links
api-version: 1.17
authors: [ TheIceNinja ]
description: My links plugin
website: store.ramatninja.tk
commands:
  discord:
    description: give the discord links
    usage: /<command>
    aliases:
      - dis
  youtube:
    description: give the yt link
    usage: /<command>
    aliases:
      - yt
  namemc:
    description: give the vote link
    usage: /<command>
    aliases:
      - vote
  store:
    description: give the store link
    usage: /<command>
    aliases:
      - shop
  links:
    description: reloading the plugin
    usage: /<command>


